services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ulab
    volumes:
      - mongodb_data:/data/db
    networks:
      - node_app
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  node_app1:
    container_name: node_app1
    image: javohirgo/node_app:latest
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ulab
    networks:
      - node_app
    command: ["npm", "start"]
    depends_on:
      mongodb: 
        condition: service_healthy

  node_app2:
    container_name: node_app2
    image: javohirgo/node_app:latest  
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ulab
    networks:
      - node_app
    command: ["npm", "start"]
    depends_on:
      mongodb:
        condition: service_healthy
    
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 81:80
    depends_on:
      - node_app1
      - node_app2
    networks:
      - node_app

networks:
  node_app:
    driver: bridge

volumes:
  mongodb_data: